config/routes.rb
Rails.application.routes.draw do
  resources :tags
  resources :categories
  resources :tag_associations
  resources :tasks
  get 'welcome/index'
  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      passwords: 'users/passwords'
  }

  root 'welcome#index'
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  validates :category, presence: false, allow_blank: true
  belongs_to :category, optional: true
  belongs_to :user
  has_many :tag_associations, dependent: :destroy
  has_many :tags, through: :tag_associations, dependent: :destroy
  self.per_page = 30


end

app/controllers/tasks_controller.rb
require 'color_converter'
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = current_user.tasks
    #@tasks = current_user.tasks.where("title LIKE ? OR note LIKE ?", "%#{params[:search]}%", "%#{params[:search]}%")
    @tasks = Task.paginate(page: params[:page])
  end


  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @tasks = Task.find(params[:id])
  end

  # GET /tasks/new
  def new
    @task = Task.new(user: current_user)
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params.merge(user: current_user))
    respond_to do |format|
      if @task.save
        format.html { redirect_to tasks_url, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to tasks_url notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:deadline_at, :title, :note, :is_done, :user_id, :category_id, :tag_id, :tag_ids => [ ])
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= simple_form_for(@task) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">

    <%= f.input :deadline_at %>

    <%= f.input :title %>

    <%= f.input :note %>

    <%= f.input :is_done %>

    <%= f.association :category, required: false %>

    <%= f.association :tags, through: :tag_associations %>

  </div>

  <div class="form-actions">
    <%= f.button :magic_submit, cancel: tasks_path  %>
  </div>

<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>
<div class="d-flex justify-content-center">
  <h1>Tasks</h1>
</div>
<% if @tasks.any? %>
<h4>Search tasks:</h4>
  <label for="searching_tasks"><input type="search" id="searching_tasks" onkeyup="searchTable()" class="form-control"></label>
  <button type="button" class="btn btn-outline-primary"><%= link_to 'Back', tasks_path %></button>
  <table class="table table-hover" id="tasks">
  <thead>
    <tr>
      <th onclick="sortTable(0)">Deadline at (click to sort by)</th>
      <th>Title</th>
      <th>Note</th>
      <th>Is done</th>
      <th onclick="sortTable(1)">Tags (click to sort by)</th>
      <th onclick="sortTable(2)">Category (click to sort by)</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.deadline_at.strftime("%B %d, %Y %H:%M") %></td>
        <td><%= task.title %></td>
        <td>
          <%= task.note != "" ? "Yes" : "No" %>
        </td>
        <td><%= task.is_done == true ? "Yes" : "No" %></td>
        <td>
          <% task.tags.each do |tag| -%>
            <div><%= tag.title %></div>
          <% end -%>
            </td>
        <td><%= if task.category != nil then link_to task.category.title, category_path(task.category) else "No" end%></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td></td>
      </tr>
    <% end %>
    <%= will_paginate @tasks %>
  </tbody>
</table>
<br>

<button type="button" class="btn btn-outline-primary"><%= link_to 'New Task', new_task_path %></button>
<%else %>
  <div class="d-flex justify-content-center">There is not any task, you need to create one.</div>
<button type="button" class="btn btn-outline-primary"><%= link_to 'New Task', new_task_path %></button>
<%end %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<button type="button" class="btn btn-outline-info"><%= link_to 'Back', tasks_path %></button>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<ul class="list-group list-group-flush">
  <li class="list-group-item"><strong>Deadline at:</strong>
    <%= @task.deadline_at %></li>
  <li class="list-group-item"><strong>Title:</strong>
    <%= @task.title %></li>
  <li class="list-group-item"><strong>Note:</strong>
    <%= @task.note %></li>
  <li class="list-group-item"><strong>Category:</strong>
  <%= @task.category_id %>
</li>
  <li class="list-group-item"><strong>Tags:</strong>
    <% @tasks.tags.each do |tag| -%>
      <div><%= link_to tag.title, tag_path(tag) %></div>
    <% end -%>
  </li>
</ul>
<br>
<button type="button" class="btn btn-outline-info"><%= link_to 'Edit', edit_task_path(@task) %></button>
<button type="button" class="btn btn-outline-info"><%= link_to 'Delete', @task,  method: :delete, data: { confirm: 'Are you sure?' } %></button>
<button type="button" class="btn btn-outline-info"><%= link_to 'Back', tasks_path %></button>