config/routes.rb
Rails.application.routes.draw do
  resources :tags
  resources :categories
  resources :tag_associations
  resources :tasks
  get 'welcome/index'
  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      passwords: 'users/passwords'
  }

  root 'welcome#index'
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  belongs_to :user
  has_many :tag_associations, dependent: :destroy
  has_many :tasks, through: :tag_associations, dependent: :destroy
  require 'color_converter'
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = current_user.tags.order(title: :ASC)
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
    @tag = Tag.find(params[:id])
  end

  # GET /tags/new
  def new
    @tag = Tag.new(user: current_user)
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params.merge(user: current_user))

    respond_to do |format|
      if @tag.save
        format.html { redirect_to tags_url, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to tags_url, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:title, :color, :task_ids => [ ])
    end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<%= simple_form_for(@tag) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">

    <%= f.input :title %>

    <%= f.input :color, as: :color %>

  </div>

  <div class="form-actions">
    <%= f.button :magic_submit, cancel: tags_path  %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing Tag</h1>

<%= render 'form', tag: @tag %>

app/views/tags/index.html.erb
<p id="notice"><%= notice %></p>

<div class="d-flex justify-content-center"><h1>Tags</h1></div>

<% if @tags.any? %>
<table class="table table-hover">
  <thead>
    <tr>
      <th>ID</th>
      <th>Title</th>
      <th>Color</th>
      <th>Creation Date</th>
      <th>Date of change</th>
      <th>Count of tasks</th>
      <th></th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.id %></td>
        <td><%= tag.title %></td>
        <td><%= ColorConverter.rgb(tag.color) %>
          <svg width="20" height="20">
            <rect width="20" height="20" style="fill:<%= tag.color%>" />
          </svg>
        </td>
        <td><%= tag.created_at.strftime("%B %d, %Y %H:%M") %></td>
        <td><%= tag.updated_at.strftime("%B %d, %Y %H:%M") %></td>
        <td><%= tag.tasks.count %></td>
        <td><%= link_to 'Show', tag %></td>
        <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
        <td><%= link_to 'Delete', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<button type="button" class="btn btn-outline-primary"><%= link_to 'New Tag', new_tag_path %></button>
<%else %>
  There is not any tag, you need to create one.
  <button type="button" class="btn btn-outline-primary"><%= link_to 'New Tag', new_tag_path %></button>
<%end %>

app/views/tags/new.html.erb
<h1>New Tag</h1>

<%= render 'form', tag: @tag %>

<button type="button" class="btn btn-outline-info"><%= link_to 'Back', tags_path %></button>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<ul class="list-group list-group-flush">
  <li class="list-group-item"><strong>ID:</strong>
    <%= @tag.id %></li>
  <li class="list-group-item"><strong>Title:</strong>
    <%= @tag.title %></li>
  <li class="list-group-item"><strong>Color:</strong>
    <%= ColorConverter.rgb(@tag.color) %>
    <svg width="20" height="20">
      <rect width="20" height="20" style="fill:<%= @tag.color%>" />
    </svg>
  </li>
  <li class="list-group-item"><strong>Creation Date:</strong>
    <%= @tag.created_at.strftime("%B %d, %Y %H:%M") %></li>
  <li class="list-group-item"><strong>Date of change:</strong>
    <%= @tag.updated_at.strftime("%B %d, %Y %H:%M") %></li>
  <li class="list-group-item"><strong>Count of tasks:</strong>
    <%= @tag.tasks.count %></li>
  <li class="list-group-item"><strong>Tasks:</strong>
    <% @tag.tasks.each do |task| -%>
      <div><%= link_to task.title, task_path(task) %></div>
    <% end -%>
  </li>
</ul>
<br>
<button type="button" class="btn btn-outline-info"><%= link_to 'Edit', edit_tag_path(@tag) %></button>
<button type="button" class="btn btn-outline-info"><%= link_to 'Back', tags_path %></button>