config/routes.rb
Rails.application.routes.draw do
  resources :tags
  resources :categories
  resources :tag_associations
  resources :tasks
  get 'welcome/index'
  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      passwords: 'users/passwords'
  }

  root 'welcome#index'
end

app/models/category.rb
class Category < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  belongs_to :user
  has_many :tasks, dependent: :destroy
  require 'color_converter'
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = current_user.categories.order(title: :ASC)
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])
  end

  # GET /categories/new
  def new
    @category = Category.new(user: current_user)
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params.merge(user: current_user))

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_url, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to categories_url, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:title, :color, :task_ids => [ ])
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= simple_form_for(@category) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">

    <%= f.input :title %>

    <%= f.input :color, as: :color %>

  </div>

  <div class="form-actions">
    <%= f.button :magic_submit, cancel: categories_path %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<div class="d-flex justify-content-center"><h1>Categories</h1></div>

<% if @categories.any? %>
<table class="table table-hover">
  <thead>
    <tr>
      <th>ID</th>
      <th>Title</th>
      <th>Color</th>
      <th>Count of Tasks</th>
      <th>Creation Date</th>
      <th>Date of change</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.id %></td>
        <td><%= category.title %></td>
        <td><%= ColorConverter.rgb(category.color) %>
          <svg width="20" height="20">
            <rect width="20" height="20" style="fill:<%= category.color%>" />
          </svg>
        </td>
        <td><%= category.tasks.count %></td>
        <td><%=category.created_at.strftime("%B %d, %Y %H:%M") %></td>
        <td><%= category.updated_at.strftime("%B %d, %Y %H:%M") %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Delete', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<button type="button" class="btn btn-outline-primary"><%= link_to 'New Category', new_category_path %></button>
<% else %>
  There is not any category, you need to create one.
<button type="button" class="btn btn-outline-primary"><%= link_to 'New Category', new_category_path %></button>
<% end %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<button type="button" class="btn btn-outline-primary"><%= link_to 'Back', categories_path %></button>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<ul class="list-group list-group-flush">
  <li class="list-group-item"><strong>ID:</strong>
    <%= @category.id %></li>
  <li class="list-group-item"><strong>Title:</strong>
    <%= @category.title %></li>
  <li class="list-group-item"><strong>Color:</strong>
    <%= ColorConverter.rgb(@category.color) %>
    <svg width="20" height="20">
      <rect width="20" height="20" style="fill:<%= @category.color%>" />
    </svg>
  </li>
  <li class="list-group-item"><strong>Creation Date:</strong>
    <%= @category.created_at.strftime("%B %d, %Y %H:%M") %>
  </li>
  <li class="list-group-item"><strong>Date of change:</strong>
    <%= @category.updated_at.strftime("%B %d, %Y %H:%M") %>
  </li>
  <li class="list-group-item"><strong>Tasks:</strong>
    <% @category.tasks.each do |task| -%>
      <div><%= link_to task.title, task_path(task) %></div>
    <% end -%>
  </li>
</ul>
<br>
<button type="button" class="btn btn-outline-info"><%= link_to 'Edit', edit_category_path(@category) %></button>
<button type="button" class="btn btn-outline-info"><%= link_to 'Back', categories_path %></button>